version: "3.7"
services:
  server:
    build: .
    image: jvpelai/my-list:latest
    container_name: server
    depends_on:
      - database
    ports:
      - "8000:8000"
      - "3000:3000"
    env_file:
      - ./packages/server/.env
  database:
    image: postgres:13
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres-data:
    driver: azure_file
    driver_opts:
      share_name: postgres-share-data
      storage_account_name: mylistdockerstorage
