version: "3.7"
services:
  server:
    build: .
    container_name: server
    depends_on:
      - "database"
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - JWT_SECRET=2DBB932B851829D796E248FB54B92
  database:
    image: postgres:13
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    volumes:
      - dbData:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  dbData:
